({
  plugin: 'oldendevPlugins/crud',
  endpoint: 'registry',
  entities: {
    Doctor: [
      'get',
      'select',
      'subscribe',
      'create',
      'update',
      'delete',
      'schema',
    ],
    Patient: [
      'get',
      'select',
      'subscribe',
      'create',
      'update',
      'delete',
      'schema',
    ],
    Reason: [
      'get',
      'select',
      'subscribe',
      'create',
      'update',
      'delete',
      'schema',
    ],
    Calendar: [
      'get',
      'select',
      'subscribe',
      'create',
      'update',
      'delete',
      'schema',
    ],
    City: [
      'get',
      'select',
      'subscribe',
      'create',
      'update',
      'delete',
      'schema',
    ],
    Country: [
      'get',
      'select',
      'subscribe',
      'create',
      'update',
      'delete',
      'schema',
    ],
    DoctorsSchedule: [
      'get',
      'select',
      'subscribe',
      'create',
      'update',
      'delete',
      'schema',
    ],
  },
});
